<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>stig</string>
	</array>
	<key>name</key>
	<string>StigScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.package.stig</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(package)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*\*(?!/)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.stig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.stig</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment.block.tig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.documentation.stig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btrue\b</string>
			<key>name</key>
			<string>constant.language.boolean.true.stig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bfalse\b</string>
			<key>name</key>
			<string>constant.language.boolean.false.stig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bnull\b</string>
			<key>name</key>
			<string>constant.language.null.stig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bunknown\b</string>
			<key>name</key>
			<string>constant.language.unknown.stig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(else|if|as|and|or|not)\b</string>
			<key>name</key>
			<string>keyword.control.stig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(int|str)\b</string>
			<key>name</key>
			<string>storage.type.stig</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(new|is|where|effecting)\b|&lt;-|%|\*|\-|\+|\*=|==|=|!=|&lt;=|&gt;=|&lt;|&gt;|\?|\:|\:\:|\+=|%=|\|=|\-=|~|~=|&amp;=|\^=|\b(in|new)\b</string>
			<key>name</key>
			<string>keyword.operator.stig</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>handles integer and decimal numbers</string>
			<key>match</key>
			<string>(?x:-?(?:0|[1-9]\d*)(?:(?:\.\d+)?(?:[eE][+-]?\d+)?)?)</string>
			<key>name</key>
			<string>constant.numeric.stig</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\.)[a-zA-Z0-9_-]+</string>
			<key>name</key>
			<string>entity.other.attribute-name.class.stig</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(['"])</string>
			<key>end</key>
			<string>(?&lt;!\\)\1</string>
			<key>name</key>
			<string>string.quoted.stig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.stig</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.stig</string>
	<key>uuid</key>
	<string>ad7f14b4-8741-49a6-b662-f424bffe50d6</string>
</dict>
</plist>
