<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>stig</string>
	</array>
	<key>name</key>
	<string>StigScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment_multiline</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#string</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#member</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#name</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#id</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.stig</string>
		</dict>
		<key>comment_multiline</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.stig</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.stig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment_multiline</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(true|false|null|known|unknown|empty|free)\b</string>
			<key>name</key>
			<string>constant.language.stig</string>
		</dict>
		<key>control</key>
		<dict>
			<key>match</key>
			<string>\b(else_if|else|if|as|and_then|and|or_else|or|xor|not|assert|delete)\b</string>
			<key>name</key>
			<string>keyword.control.stig</string>
		</dict>
		<key>id</key>
		<dict>
			<key>match</key>
			<string>[0-9A-Fa-f]{8}-([0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}</string>
			<key>name</key>
			<string>constant.numeric.id.stig</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>match</key>
			<string>\b(package|exists|keys|new|length_of|now|real|with|reduce|reverse_of|session_id|sorted_by|start|test|that|time_diff|time_pnt|user_id|rhs|lhs|new|desc|asc|is|from|in|id|given|effecting|where)\b</string>
			<key>name</key>
			<string>support.constant.js</string>
		</dict>
		<key>member</key>
		<dict>
			<key>match</key>
			<string>\.[a-zA-Z_][a-zA-Z0-9_]*</string>
			<key>name</key>
			<string>entity.other.attribute-name.class.stig</string>
		</dict>
		<key>name</key>
		<dict>
			<key>match</key>
			<string>[_a-zA-Z][_a-zA-Z0-9]*</string>
			<key>name</key>
			<string>variable.name.stig</string>
		</dict>
		<key>numbers</key>
		<dict>
			<key>match</key>
			<string>(?x:-?(?:0|[1-9]\d*)(?:(?:\.\d+)?(?:[eE][+-]?\d+)?)?)</string>
			<key>name</key>
			<string>constant.numeric.stig</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>match</key>
			<string>!|!=|#|%|&amp;|\*|\*\*|\+|\-|\.|-&gt;|\.\.|/|&lt;-|&lt;=|&lt;\[|\]&gt;|&lt;\{|\}&gt;|=|==|&lt;|&gt;=|\?|\^|\||\*=|==|&lt;|&gt;</string>
			<key>name</key>
			<string>keyword.operator.stig</string>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>r?(['"])</string>
			<key>end</key>
			<string>(?&lt;!\\)\1</string>
			<key>name</key>
			<string>string.quoted.stig</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.stig</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>match</key>
			<string>\b(int|str|bool)\b</string>
			<key>name</key>
			<string>storage.type.stig</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.stig</string>
	<key>uuid</key>
	<string>ad7f14b4-8741-49a6-b662-f424bffe50d6</string>
</dict>
</plist>
